SommerExam/Models/ErrorViewModel.cs
using System;

namespace SommerExam.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SommerExam/Models/Location.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace SommerExam.Models
{
    public class Location
    {

        [BindNever]
        public int LocationId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Number")]
        public string AddressNumber { get; set; }

        [Required]
        [Display(Name = "Zip Code")]
        [DataType(DataType.PostalCode)]
        public string PostalCode { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string City { get; set; }

        public List<Sensor> Sensors = new List<Sensor>();

    }
}

SommerExam/Models/Sensor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.CodeAnalysis;

namespace SommerExam.Models
{
    public class Sensor
    {
        [BindNever]
        public int Id { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Please inter a whole number")]
        public int LocationId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string TreeSpecies { get; set; }

        [Required]
        [MaxLength(16)]
        public string SensorId { get; set; }

        [Required]
        public double Longitude { get; set; }

        [Required]
        public double Latitude { get; set; }
    }
}

SommerExam/ViewModels/DetailViewModel.cs
using System.Collections.Generic;
using SommerExam.Models;

namespace SommerExam.ViewModels
{
    public class DetailViewModel
    {
        public Location Location { get; set; }
        public List<Sensor> Sensors { get; set; }
    }
}

SommerExam/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SommerExam.Data;
using SommerExam.Models;

namespace SommerExam.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ApiController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        public ApiController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("{name}")]
        public ActionResult<List<Location>> GetLocations(string name)
        {
            var locations = _context.Locations.Where(p => p.Name.Contains(name)).ToList();

            return locations;
        }
    }
}

SommerExam/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SommerExam.Models;

namespace SommerExam.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SommerExam/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SommerExam.Data;
using SommerExam.Models;
using SommerExam.ViewModels;

namespace SommerExam.Controllers
{
    public class LocationsController : Controller
    {
        private const int LocationsPerPage = 5;

        private readonly ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Locations.ToListAsync());
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }

            var tempSensors = _context.Sensors.Where(p => p.LocationId == location.LocationId).ToList();


            var viewModel = new DetailViewModel
            {
                Location = location,
                Sensors = tempSensors
            };


            return View(viewModel);
        }

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LocationId,Name,Address,AddressNumber,PostalCode,City")] Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }


        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations
                .FirstOrDefaultAsync(m => m.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _context.Locations.FindAsync(id);
            _context.Locations.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.LocationId == id);
        }
    }
}

SommerExam/Controllers/SensorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SommerExam.Data;
using SommerExam.Models;

namespace SommerExam.Controllers
{
    public class SensorController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SensorController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> AddSensor(int id)
        {
            var location = await _context.Locations.FirstOrDefaultAsync(p => p.LocationId == id);
            if (location == null)
                return NotFound();

            return View(new Sensor() { LocationId = location.LocationId });
        }
        [HttpPost]
        public async Task<IActionResult> AddSensor(Sensor sensor)
        {
            if (ModelState.IsValid)
            {
                var location = await _context.Locations.FirstOrDefaultAsync(p => p.LocationId == sensor.LocationId);
                if (location != null)
                    _context.Sensors.Add(sensor);
                await _context.SaveChangesAsync();
                return RedirectToAction("SensorAdded");
            }
            return View(sensor);
        }

        public IActionResult SensorAdded()
        {
            return View();
        } 
    }
}

SommerExam/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    @if (!User.Identity.IsAuthenticated) {
        <h2 class="display-4">Welcome, please log in to proceed!</h2>
    }
    @if (User.Identity.IsAuthenticated)
    {
        <h2 class="display-4"> Welcome Back!</h2>
    }
    <img src="images/trees.png" alt="" class="embed-responsive"/>
</div>

SommerExam/Views/Locations/Create.cshtml
@model SommerExam.Models.Location

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressNumber" class="control-label"></label>
                <input asp-for="AddressNumber" class="form-control" />
                <span asp-validation-for="AddressNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="hyperlinks">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SommerExam/Views/Locations/Delete.cshtml
@model SommerExam.Models.Location

@{
    ViewData["Title"] = "Delete";
}

<h3 class="alert-1">Are you sure you want to delete this location?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddressNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddressNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LocationId"  />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="hyperlinks">Back to List</a>
    </form>
</div>

SommerExam/Views/Locations/Details.cshtml
@model DetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.LocationId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.LocationId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.AddressNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.AddressNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.PostalCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.City)
        </dd>
    </dl>
</div>
<div class="row">
    <table class="table table-light table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Sensors[0].TreeSpecies)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sensors[0].Longitude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sensors[0].Latitude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sensors[0].SensorId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Sensors)
            {
                <tr>
                    <td>
                        @item.TreeSpecies
                    </td>
                    <td>
                        @item.Longitude
                    </td>
                    <td>
                        @item.Latitude
                    </td>
                    <td>
                        @item.SensorId
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index" class="hyperlinks">Back to List</a>
</div>

SommerExam/Views/Locations/Index.cshtml
@model IEnumerable<Location>

@{
    ViewData["Title"] = "Locations";
}

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<h1>Locations</h1>

<p class="hyperlinks">
    <a asp-action="Create">Create New</a>
</p>

<hr />
<table class="table table-light table-hover">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.LocationId)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.AddressNumber)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.City)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="col">
                    @Html.DisplayFor(modelItem => item.LocationId)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddressNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostalCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.LocationId" class="hyperlinks">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.LocationId" class="hyperlinks">Delete</a> |
                    <a asp-action="AddSensor" asp-controller="Sensor" class="hyperlinks"
                       asp-route-id="@item.LocationId">Add Sensor</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="Vue">

    <div class="box">
        <div class="container-1">
            <span class="icon"><i class="fa fa-search"></i></span>
            <input id="searchString" type="search" placeholder="Search..." />
            <input type="submit" value="Search" class="btn searchButton" v-on:click="getData" />
        </div>
    </div>

    <h3>Searched locations</h3>

    <table class="table table-light table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.LocationId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AddressNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PostalCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="location in locations">
                <td>{{location.locationId}}</td>
                <td>{{location.name}}</td>
                <td>{{location.address}}</td>
                <td>{{location.addressNumber}}</td>
                <td>{{location.postalCode}}</td>
                <td>{{location.city}}</td>
            </tr>
        </tbody>
    </table>
</div>

@section Scripts {
    <script src="~/js/Vue.js" asp-append-version="false"></script>
}

SommerExam/Views/Sensor/AddSensor.cshtml
@model Sensor

@{
    ViewBag.Title = "title";
}

<h1>Add sensor</h1>

<h4>Sensor</h4>
<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddSensor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TreeSpecies" class="control-label"></label>
                <input asp-for="TreeSpecies" class="form-control" />
                <span asp-validation-for="TreeSpecies" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SensorId" class="control-label"></label>
                <input asp-for="SensorId" class="form-control" />
                <span asp-validation-for="SensorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

SommerExam/Views/Sensor/SensorAdded.cshtml
@{
    ViewData["Title"] = "SensorAdded";
}

<h1 class="align-content-center thank" >Sensor added, thank you for your contribution!</h1>

SommerExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SommerExam</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script type="text/javascript" src="https://unpkg.com/vue@2.6.10/dist/vue.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SommerExam</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Locations" asp-action="Index">Locations</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - SommerExam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>